#!/usr/bin/env python3
from middlewared.utils.rootfs import ReadonlyRootfsManager

"""Chelsio's script needs write access to firmware files
inside /usr/lib. Since we have an immutable rootfs, we
need to temporarily set readonly=off for /usr/lib."""


def main():
    import sys

    # chelsio_adapter_config.py script lives here
    sys.path.insert(1, "/usr/local/libexec")
    import chelsio_adapter_config

    with ReadonlyRootfsManager(force_usr_rw=True) as rrm:
        rrm.make_writeable()
        chelsio_adapter_config.main()


if __name__ == "__main__":
    main()
